### ISSUE TITLE
Status of the riscv-buildroot

### ISSUE THREAD

**Issue by AmeyaVS** [riscv/riscv-buildroot#1]
Has the project been mainlined in the buildroot project?

As per the comment in the Wiki page:

> 25th September 2018
> * All changes up to this point have now been committed to the official Buildroot repository.

What version should be used for buildroot to create riscv32 and riscv64 images?

**Comment by markcorbinuk** [comment]
64-bit RISC-V support is in the mainline Buildroot project. It has been available in the master branch since 12th September 2018 and is also available in the 2018.11 release branch. Package support for RISC-V is continuously improving. You can use either of these branches for riscv64 depending on the whether they support the packages that you need.

Support for 32-bit RISC-V has been submitted to the Buildroot mailing list, but hasn't been added yet. The 32-bit patches are available [here](http://patchwork.ozlabs.org/project/buildroot/list/?series=71965)

**Comment by AmeyaVS** [comment]
Hello @markcorbinuk ,

Thank you for the reference for the patches, I will look into it.
Is there a general timeline available so we can expect mainline support?

Thank you,
Ameya Vikram Singh

**Comment by markcorbinuk** [comment]
I've posted a message on the Buildroot IRC channel to ask people to review/test the patches if possible.

If you have a chance to test them yourself, you could post a 'Tested-by' tag to the Buildroot mailing list - this might help to speed things along.

Otherwise, I will raise the topic at the Buildroot developers meeting during the first week of February 2019 and see if I can get the patches accepted then.

**Comment by palmer-dabbelt** [comment]
IT sounds like we should go ahead and deprecate this repo (riscv-buildroot) now that there's an upstream version.  Is anyone opposed?

**Comment by markcorbinuk** [comment]
This repo is definitely obsolete now. Maybe we could leave a 'readme' to point people to the upstream version for a while?

**Comment by palmer-dabbelt** [comment]
https://github.com/riscv/riscv-buildroot/pull/2

**Comment by AmeyaVS** [comment]
@palmer-dabbelt I am not in favor of just purging the whole repository.
It would be better if the `README.md` and status bar reflect the links to the mainline.

With highlighted/bold text that this repo is obsolete.

![image](https://user-images.githubusercontent.com/6262562/51048564-4d518300-15f1-11e9-9979-991f672bdaba.png)

**Comment by jeremybennett** [comment]
I think this is a case where being ruthless is the correct approach. Few people actually look at the README - they'll just use the same old link.

With this change, their build will fail, they'll see there is only one file, read what it says and then change the link.

We've been burned by using obsolete repos which are marked as such in the README, but remain functional but very out of date.

**Comment by palmer-dabbelt** [comment]
@jeremybennett ya, I agree :).  If you see any others let me know, I'm sure there's a lot of these at github.com/riscv .
